version: '3.3'
services:
  postgres:
    image: "postgres:9.6-alpine"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
  nginx:
    image: "nginx:alpine"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /static:/static
  backend:
    image: "ppeczek/wugensui-backend:v1"
    environment:
      - "POSTGRES_PORT_5432_TCP_PORT=5432"
      - "POSTGRES_PORT_5432_TCP_ADDR=postgres"
      - "DJANGO_SETTINGS_MODULE=wugensui.settings.local"
#  frontend:
#    image: "wugensui-frontend:v1"
#    ports:
#      - "5000:5000"
volumes:
  redis-data:
  postgres-data:
