apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: wugensui
    version: v1
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: wugensui
        version: v1
    spec:
      terminationGracePeriodSeconds: 5
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: ssl
        secret:
          secretName: ssl
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /_healthz
            port: 80
          initialDelaySeconds: 3
          timeoutSeconds: 2
          failureThreshold: 2
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx
          name: nginx-config
        - name: ssl
          mountPath: /certs
          readOnly: true
