# Generated by Django 2.0.1 on 2018-04-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('video_path', models.FileField(blank=True, null=True, upload_to='', verbose_name='video')),
                ('state', models.IntegerField(choices=[(1, 'not processed'), (2, 'creating pattern'), (3, 'processing video'), (4, 'saving results'), (5, 'finished')], default=1)),
                ('corner_a_x', models.IntegerField(blank=True, null=True, verbose_name='corner A X')),
                ('corner_a_y', models.IntegerField(blank=True, null=True, verbose_name='corner A Y')),
                ('corner_b_x', models.IntegerField(blank=True, null=True, verbose_name='corner B X')),
                ('corner_b_y', models.IntegerField(blank=True, null=True, verbose_name='corner B Y')),
                ('corner_c_x', models.IntegerField(blank=True, null=True, verbose_name='corner C X')),
                ('corner_c_y', models.IntegerField(blank=True, null=True, verbose_name='corner C Y')),
                ('corner_d_x', models.IntegerField(blank=True, null=True, verbose_name='corner D X')),
                ('corner_d_y', models.IntegerField(blank=True, null=True, verbose_name='corner D Y')),
                ('pattern', models.ImageField(blank=True, null=True, upload_to='')),
                ('paths', models.ImageField(blank=True, null=True, upload_to='')),
                ('kalman_paths', models.ImageField(blank=True, null=True, upload_to='')),
                ('result', models.FileField(blank=True, null=True, upload_to='')),
                ('kalman_result', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
