# Generated by Django 2.0.1 on 2018-01-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wugensui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='pattern',
            field=models.ImageField(blank=True, null=True, upload_to='results', verbose_name='pattern'),
        ),
    ]
