# Generated by Django 2.0.1 on 2018-07-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wugensui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='state',
            field=models.IntegerField(choices=[(1, 'not processed'), (2, 'creating pattern'), (3, 'processing video'), (4, 'saving results'), (5, 'finished'), (6, 'error')], default=1),
        ),
    ]
